import QueryProvider from "@/contexts/queryContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Progress from "@/components/ui/elements/progress";
import { UserProvider } from "@/contexts/userContext";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spyne Car Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <QueryProvider>
            <Suspense>{children}</Suspense>
            <Toaster richColors />
            <Progress />
          </QueryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
